spring:
  redis:
    host: localhost
    port: 6379
  session:
    store-type: redis
    redis:
      namespace: cgroup:session
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: AdmiN
    url: jdbc:postgresql://localhost:5432/cgroup-int
    dialect: org.hibernate.dialect.PostgreSQLDialect
    hikari:
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      connection-test-query: SELECT 1
      maximum-pool-size: 8
      minimum-idle: 3
      initialization-fail-timeout: 2000
      isolate-internal-queries: true
      validation-timeout: 3000
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
      database: postgresql
      database-platform: org.hibernate.dialect.PostgreSQLDialect

server:
  compression:
    enabled: true
    mime-types:
      - application/json
        application/xml
    min-response-size: 2KB
  servlet:
    session:
      timeout: 60

app:
  config:
    allowed:
      origin: ${ALLOWED_ORIGIN:http://localhost:4200}